### DISCUSSION TITLE
config file seems not working

### DISCUSSION THREAD

**Discussion by adamspd** [verdaccio/charts#81] [Q&A] [answered]
Hello everyone, I have configured verdaccio on a centos server and followed the tuto in the documentation. I used a docker container and my repository tree looks like this : 
``` 
/root/verdacio/
         |_____ conf/
         |       |___config.yaml 
         |_____ logo
         |      |____mylogo.ico
         |      |____mylogo.png
         |_____ plugins
         |_____ storage
```

My config.yaml file look like this :
```
storage: /root/verdaccio/storage
plugins: /root/verdaccio/plugins
web:
  enable: true
  title: "MyStartUp"
  logo: /root/verdaccio/logo/mylogo.png
  gravatar: true
  scope: "@mystartup"
  sort_packages: asc | desc
  darkmode: true
  favicon: /root/verdaccio/logo/mylogo.ico
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@mystartup/':
    access: $authenticated
    publish: $authenticated
  '@*/*':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
  '**':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
middlewares:
  audit:
    enabled: true
max_body_size: 100mb
logs:
  - {type: stdout, format: pretty, level: http}

```
My questions are ? 
Why do I find my packages (when I publish one) in ```/var/lib/docker/volumes/someID/_data/data``` ? I had a hard time finding them.
Why the logo doesn't work and I still have verdaccio's logo in the UI, the title remains verdaccio and even though I'm not authenticated, when I go to the web ui, I still can download the packages (not yet tested via the terminal) ?

I thought it could be a problem due to the location of the conf file (since I saw in one of the youtube video that the guy had something like ~/verdaccio/conf/verdaccio/config.yaml) and I did the same, restart the docker container but my problem remained. 

Thanks so much for your time.
