### ISSUE TITLE
Pod status 'Pending'

### ISSUE THREAD

**Issue by exipnus** [verdaccio/charts#106]
Hi,

I tried to install using helm chart following the documentation:

```
sudo microk8s helm repo add verdaccio https://charts.verdaccio.org
sudo microk8s helm repo update
sudo microk8s kubectl create configmap verdaccio-config --from-file ./conf/config.yaml -n exipnus
sudo microk8s helm install npm --set existingConfigMap=verdaccio-config verdaccio/verdaccio -n exipnus

sudo microk8s kubectl describe pod/npm-verdaccio-f768bb697-jfqfn
```

and I get:

![image](https://user-images.githubusercontent.com/85255193/193515150-9625efeb-4810-43ef-a454-fe63c2ec7afd.png)

when describing the pod:

```
Name:             npm-verdaccio-f768bb697-jfqfn
Namespace:        exipnus
Priority:         0
Service Account:  default
Node:             <none>
Labels:           app=npm-verdaccio
                  app.kubernetes.io/instance=npm
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=verdaccio
                  app.kubernetes.io/version=5.15.4
                  helm.sh/chart=verdaccio-4.9.2
                  pod-template-hash=f768bb697
Annotations:      checksum/config: 12f9d201dff56809aa159eaf93d6848e5ea7fa7205bfbbcf1b2cc303c4b7e5de
                  checksum/htpasswd-secret: 4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/npm-verdaccio-f768bb697
Containers:
  verdaccio:
    Image:        verdaccio/verdaccio:5.15.4
    Port:         4873/TCP
    Host Port:    0/TCP
    Liveness:     http-get http://:http/-/ping delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:http/-/ping delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-24spz (ro)
      /verdaccio/conf from config (ro)
      /verdaccio/storage from storage (rw)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      verdaccio-config
    Optional:  false
  storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  npm-verdaccio
    ReadOnly:   false
  kube-api-access-24spz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  35s   default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```

This is my config file:

```
storage: /verdaccio/storage/data

priorityClass:
  enabled: true
  name: "high-priority"

persistence:
  enabled: true
  storageClass: ""

web:
  title: Verdaccio
  showSettings: false
  showFooter: false

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

log: { type: stdout, format: pretty, level: http }

```
I also tried without the following 

```
priorityClass:
  enabled: true
  name: "high-priority"

persistence:
  enabled: true
  storageClass: ""
```

Or any combination of them.

Below is the output of the following command:

```
sudo microk8s kubectl describe deployment.apps/npm-verdaccio -n exipnus
```

```
Name:               npm-verdaccio
Namespace:          exipnus
CreationTimestamp:  Mon, 03 Oct 2022 10:05:22 +0200
Labels:             app=npm-verdaccio
                    app.kubernetes.io/instance=npm
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=verdaccio
                    app.kubernetes.io/version=5.15.4
                    helm.sh/chart=verdaccio-4.9.2
Annotations:        deployment.kubernetes.io/revision: 1
                    meta.helm.sh/release-name: npm
                    meta.helm.sh/release-namespace: exipnus
Selector:           app.kubernetes.io/instance=npm,app.kubernetes.io/name=verdaccio
Replicas:           1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:           app=npm-verdaccio
                    app.kubernetes.io/instance=npm
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=verdaccio
                    app.kubernetes.io/version=5.15.4
                    helm.sh/chart=verdaccio-4.9.2
  Annotations:      checksum/config: 12f9d201dff56809aa159eaf93d6848e5ea7fa7205bfbbcf1b2cc303c4b7e5de
                    checksum/htpasswd-secret: 4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945
  Service Account:  default
  Containers:
   verdaccio:
    Image:        verdaccio/verdaccio:5.15.4
    Port:         4873/TCP
    Host Port:    0/TCP
    Liveness:     http-get http://:http/-/ping delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:http/-/ping delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /verdaccio/conf from config (ro)
      /verdaccio/storage from storage (rw)
  Volumes:
   config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      verdaccio-config
    Optional:  false
   storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  npm-verdaccio
    ReadOnly:   false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    True    ReplicaSetUpdated
OldReplicaSets:  <none>
NewReplicaSet:   npm-verdaccio-f768bb697 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  21s   deployment-controller  Scaled up replica set npm-verdaccio-f768bb697 to 1
```

It seems that no PersistentVolume is created.

Am I doing something wrong?

Thank you
