### ISSUE TITLE
How to update The Heml to use V4

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/charts#13]
Thoughts? 

Context: 

* We might have folder/permissions issues (mostly reported by users using v4)

https://verdaccio.org/blog/2019/05/13/the-new-docker-image-verdaccio-4

**Comment by juanpicado** [comment]
@dlouzan https://github.com/helm/charts/pull/6957 actually made a good improvement while ago.

**Comment by orefalo** [comment]
create a file called values.yaml
```
image:
  repository: verdaccio/verdaccio
  tag: 4.6.2
  pullPolicy: IfNotPresent
```

run:
helm install verdaccio verdaccio/verdaccio --values values.yaml 

works like a charm
