### ISSUE TITLE
Read-only error when addUser

### ISSUE THREAD

**Issue by andreapigatto** [verdaccio/charts#148]
Hi,
I installed successfully verdaccio via this helm chart but I'm facing a E500 when I try to run addUser command via terminal.
Checking the pod log I see:
`Error: EROFS: read-only file system, open '/verdaccio/storage/htpasswd'`

I'm installing verdaccio as a subchart with these values:
````
verdaccio:
  configMap: |
    storage: /verdaccio/storage/data

    web:
      # WebUI is enabled as default, if you want disable it, just uncomment this line
      #enable: false
      title: Verdaccio

    auth:
      htpasswd:
        file: /verdaccio/storage/htpasswd
        algorithm: bcrypt
        rounds: 10

    uplinks:
      npmjs:
        url: https://registry.npmjs.org/
        agent_options:
          keepAlive: true
          maxSockets: 40
          maxFreeSockets: 10

    packages:
      '@company/*':
        access: $authenticated
        publish: $authenticated
        unpublish: $authenticated
      '@*/*':
        access: $authenticated
        publish: $authenticated
        proxy: npmjs
      '**':
        access: $authenticated
        publish: $authenticated
        proxy: npmjs

    # log settings
    log: {type: stdout, format: pretty, level: http}
  secrets:
    htpasswd:
    - username: "verdaccio"
      password: "verdaccio"
  ingress:
    enabled: true
    className: "nginx"
    paths:
      - /
    extraPaths: [ ]
    hosts:
      - verdaccio.my-monorepo.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts:
          - verdaccio.my-monorepo.com
        secretName: verdaccio-tls # as expected by argocd-server
```

Verdaccio is running correctly at https://verdaccio.my-monorepo.com. 
I'm able to login on the UI with the verdaccio user defined in values above.

When I try to run addUser to add a user I get the error I mentioned above.

Checking the templates of the chart I saw this:
```
...
      - mountPath: /verdaccio/storage/htpasswd
        name: htpasswd
        subPath: htpasswd
        readOnly: true
...

```

I'm guessing if that readOnly can be the issue preventing to update the file and add users.
That property seems not possible to overwrite via values but hardcoded on the code of the template.

Am I missing something?
I'm not that experienced with npm registry and htpasswd. Is there a way to retrieve from the verdaccio user used for the UI the token for the .npmrc file? So that I can use the same user?

In any case add multiple users to be used in verdaccio seems a must have feature. Any ideas? 

Thanks!
