### ISSUE TITLE
Unable to change size with persistence.existingClaim

### ISSUE THREAD

**Issue by himanshumehta1114** [verdaccio/charts#22]
# Issue
I am trying to achieve the backup and restore system for my verdaccio.
To create the backup, I created the snapshot of the persistent disk attached to the persistentVolume created by helm chart. 
And to restore it, I created the persistent disk from my snapshot. and I created the persistenceVolume and persistenceVolumeClaim attaching newly created disk to it and upgraded the release with 
`helm upgrade <release_name> verdaccio/verdaccio --install --set persistence.exisitingClaim=<pv_with_restored_disk>`
 But now I'm not able to resize the existing PVC on passing `persistence.size`.

# How to reproduce
Create new PersistenceVolumeClaim
```
cat <<EOF | kubectl create -f -
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: verdaccio-verdaccio
  name: new-verdaccio-claim
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
EOF
```

Attach to release and change the size
```
$ helm upgrade verdaccio verdaccio/verdaccio --install --set persistence.existingClaim=new-verdaccio-claim --set persistence.size=32Gi
```

# Expected
PVC should resize.
