### ISSUE TITLE
Help: How do I limit the access to predefined users

### ISSUE THREAD

**Issue by frossi85** [verdaccio/charts#23]
Hi,

I am new at Verdaccio. I used this to deploy Verdaccio in my Kubernetes cluster in Digital Ocean, but even after seen that has the htpasswd enabled everyone can add a user with `npm adduser --registry {VERDACCIO_HOST}`. Besides the max_users is there a way to limit users to be added without some admin add them to the htpasswd file?

I added two users then I checked the htpasswd file and I can only see the one which I think it was created during the installation. So I do not understand well the purpose of that file if everyone with the host can add himself as a publisher.  

I did not find any useful info on how to admin users or limit user access. Could u help me with this?

Thanks a lot in advance.

**Comment by orefalo** [comment]
I used a customer values.yaml file,

In it, the entry htpasswd will be used to digest security
go to https://hostingcanada.org/htpasswd-generator/
create yourself a login/password using MD5 (important)
ie. test:$apr1$9snlk40p$ZxeHAQ7jsSt3qoRptjBh./

then in the values.yaml file, copy paste the value as follow. Note that you can add more than one entry.

```
htpasswd: |
  test:$apr1$9snlk40p$ZxeHAQ7jsSt3qoRptjBh./:autocreated 2019-07-06T11:54:15.003Z
```

start with:
helm install verdaccio verdaccio/verdaccio --values values.yaml

**Comment by kav** [comment]
Does that work? I'm not seeing where that's consumed by the chart. Is this a missing feature or do I need to look closer?

**Comment by kav** [comment]
Looks like more folks are having trouble here https://github.com/verdaccio/verdaccio/issues/1989#issuecomment-718792309. I'll take a look and add some notes here on a design. I'd like to avoid requiring a generated htpasswd file or placing cleartext passwords in values while supporting those option as well.

Here are the possibilities (brain dumping a bit):
1. An `htpasswd` entry in values as described above (maybe already implemented).
```yaml
htpasswd: |
  test:$apr1$9snlk40p$ZxeHAQ7jsSt3qoRptjBh./:autocreated 2019-07-06T11:54:15.003Z
```
2. A `htpasswdSecret` property where the value is a secret containing the `.htpasswd` file
```yaml
htpasswdSecret: htpasswrd-secret
```
assuming you also create
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd
data:
  htpasswd: dGVzdDokYXByMSQ5c25sazQwcCRaeGVIQVE3anNTdDNxb1JwdGpCaC4vOmF1dG9jcmVhdGVkIDIwMTktMDctMDZUMTE6NTQ6MTUuMDAzWg==
```
3. A `users` array containing `username` and `password` properties
```yaml
users:
- name: test
  password: YouBetterNotUsePassword123
```
alternatively, but strangely a rare pattern in kubernetes/helm
```yaml
users:
- test: YouBetterNotUsePassword123
```
4. A `usersSecret` that contains similar
```yaml
usersSecret: accounts-secret
```
which again assumes you create a secret as:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: accounts-secret
data:
  test: WW91QmV0dGVyTm90VXNlUGFzc3dvcmQxMjM=
```

2 and 4 work better in GitOps flows so are likely what I'd use. I don't like sensitive info in my values but YMMV. 3 and 4 are obviously leaking less of the underlying abstraction vs 1 and 2 which are simpler for folks already up and running.

All four could easily be fairly trivially supported so I'm looking for feedback on design and naming mostly rather than a which one should we do, unless of course you really hate an option.

Anyone have thoughts on naming of properties (users vs perhaps accounts)?

**Comment by todpunk** [comment]
Accounts is more accurate, as it might be a team account or a system account or could be thought of as a "role" or some other principal.

The current implemented thing that I use in an install is having this (I generated the line for this comment, but there's a line for my one CI/CD account):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio-htpasswd
  namespace: npm-registry
data:
  htpasswd: |
    test:$2y$10$dy8t/9PqrcY0nlprWvhgL.p3gp5u2q9Q3a1PnEsmTK7dDCtyK7ACe
```

Then in the chart values I have 

```
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 200Gi
  volumes:
  - name: verdaccio-htpasswd-volume
    configMap:
      name: verdaccio-htpasswd
  mounts:
  - mountPath: /verdaccio/config/
    name: verdaccio-htpasswd-volume
    readOnly: true

configMap: |
  storage: /verdaccio/storage/data
  web:
    title: Verdaccio
  auth:
    htpasswd:
      file: /verdaccio/config/htpasswd
   ...
```

It might not be difficult to get that into the chart itself, but not strictly necessary either.
