### ISSUE TITLE
unexpected error: EACCES: permission denied

### ISSUE THREAD

**Issue by masterkain** [verdaccio/charts#36]
I upgraded to:

```
  chart:
    repository: https://charts.verdaccio.org
    name: verdaccio
    version: 0.16.2
  values:
    image:
      tag: 4.8.1
```
 from chart 0.13.0 with no image specified:

```
  chart:
    repository: https://charts.verdaccio.org
    name: verdaccio
    version: 0.13.0
```

and suddenly I can't `npm publish` packages due to permission issues:

```
│  error--- unexpected error: EACCES: permission denied, open '/verdaccio/storage/data/@bsmartlabs/bsmart-global-style/bsmart-global-style-1.2.1-develop-dbfb6d31.tgz.tmp-6112493514612476'
│ Error: EACCES: permission denied, open '/verdaccio/storage/data/@bsmartlabs/bsmart-global-style/bsmart-global-style-1.2.1-develop-dbfb6d31.tgz.tmp-6112493514612476'
```

I use efs.
any idea?

```
/verdaccio/storage/data $ ls -lha
total 3M
drwxr-sr-x  789 100      40051      34.0K Aug  8 00:47 .
drwxrws--x    3 root     40051       6.0K Jun 22 08:19 ..
-rw-r--r--    1 100      40051       1.3K Aug 25 02:32 .verdaccio-db.json
...

```
attached the relevant portions of my HelmRelease file

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: verdaccio
  namespace: verdaccio
spec:
  releaseName: npm
  chart:
    repository: https://charts.verdaccio.org
    name: verdaccio
    version: 0.16.2
  values:
    image:
      tag: 4.8.1
    persistence:
      storageClass: efs
    podAnnotations:
      backup.velero.io/backup-volumes: storage
    configMap: |
      storage: /verdaccio/storage/data
      max_body_size: 500mb
      ...
```
