### ISSUE TITLE
Nginx-Ingress using certificate-arn has mixed-content issues

### ISSUE THREAD

**Issue by cmille62** [verdaccio/charts#73]
Using an ARN Cert, I seem to have mixed content issues, I've tried a few diffrent annotations to correct this, but so far they all produce the same result; has anyone seen this before? Thanks!

Nginx-Ingress Versions: 
`v0.48.1`
Helm Version:
`version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}`

**Error within browser:** 
```Mixed Content: The page at 'https://npm.{url}.com/' was loaded over HTTPS, but requested an insecure favicon 'http://npm.{url}.com/-/static/favicon.ico'. This request has been blocked; the content must be served over HTTPS.```

**Deployment Pod Logs**
```
 http --- [33m200[39m, user: [1mnull[22m(192.168.36.66), req: 'GET /-/ping', bytes: [33m0[39m/[33m3[39m
8
 http --- 192.168.36.66 requested 'GET /-/ping'
7
 http --- [33m200[39m, user: [1mnull[22m(192.168.36.66), req: 'GET /-/ping', bytes: [33m0[39m/[33m3[39m
6
 http --- 192.168.36.66 requested 'GET /-/ping'
5
 http --- [33m200[39m, user: [1mnull[22m(192.168.36.66), req: 'GET /-/ping', bytes: [33m0[39m/[33m3[39m
4
 http --- 192.168.36.66 requested 'GET /-/ping'
3
 http --- [33m200[39m, user: [1mnull[22m(192.168.36.66), req: 'GET /-/ping', bytes: [33m0[39m/[33m3[39m
2
 http --- 192.168.36.66 requested 'GET /-/ping'

```

**Values File:** 

```YAML
image:
  repository: verdaccio/verdaccio
  tag: 5.1.1
  pullPolicy: IfNotPresent
  pullSecrets: []
    # - dockerhub-secret

nameOverride: ""
fullnameOverride: ""

service:
  annotations: {}
  clusterIP: ""

  ## List of IP addresses at which the service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  port: 4873
  type: ClusterIP
  # nodePort: 31873

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
##
affinity: {}

## Tolerations for nodes
tolerations: []

## Additional pod labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}

## Additional pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

replicaCount: 1

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 512Mi
  # limits:
  #   cpu: 100m
  #   memory: 512Mi

ingress:
  enabled: true
  # Set to true if you are on an old cluster where apiVersion extensions/v1beta1 is required
  useExtensionsApi: false
  paths:
    - /
  # Use this to define, ALB ingress's actions annotation based routing. Ex: for ssl-redirect
  # Ref: https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/tasks/ssl_redirect/
  extraPaths: []
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:{arn-cert}
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/scheme: internet-facing
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  tls:
  hosts:
  - npm.{url}.com

  
#   - secretName: secret
#     hosts:
#       - npm.blah.com
## Service account
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the Chart's fullname template
  name: ""

# Extra Environment Values - allows yaml definitions
extraEnvVars:
#  - name: VALUE_FROM_SECRET
#    valueFrom:
#      secretKeyRef:
#        name: secret_name
#        key: secret_key
#  - name: REGULAR_VAR
#    value: ABC

# Extra Init Containers - allows yaml definitions
extraInitContainers: []

configMap: |
  # This is the config file used for the docker images.
  # It allows all users to do anything, so don't use it on production systems.
  #
  # Do not configure host and port under `listen` in this file
  # as it will be ignored when using docker.
  # see https://github.com/verdaccio/verdaccio/blob/master/docs/docker.md#docker-and-custom-port-configuration
  #
  # Look here for more config file examples:
  # https://github.com/verdaccio/verdaccio/tree/master/conf
  #

  # path to a directory with all packages
  storage: /verdaccio/storage/data

  web:
    # WebUI is enabled as default, if you want disable it, just uncomment this line
    #enable: false
    title: Verdaccio

  auth:
    htpasswd:
      # Do not change this path if secrets htpasswd is used.
      file: /verdaccio/storage/htpasswd
      # Maximum amount of users allowed to register, defaults to "+infinity".
      # You can set this to -1 to disable registration.
      #max_users: 1000

  # a list of other known repositories we can talk to
  uplinks:
    npmjs:
      url: https://registry.npmjs.org/
      agent_options:
        keepAlive: true
        maxSockets: 40
        maxFreeSockets: 10

  packages:
    '@*/*':
      # scoped packages
      access: $all
      publish: $authenticated
      proxy: npmjs

    '**':
      # allow all users (including non-authenticated users) to read and
      # publish all packages
      #
      # you can specify usernames/groupnames (depending on your auth plugin)
      # and three keywords: "$all", "$anonymous", "$authenticated"
      access: $all

      # allow all known users to publish packages
      # (anyone can register by default, remember?)
      publish: $authenticated

      # if package is not available locally, proxy requests to 'npmjs' registry
      proxy: npmjs

  # To use `npm audit` uncomment the following section
  middlewares:
    audit:
      enabled: true

  # log settings
  logs: {type: stdout, format: pretty, level: http}
  # logs: {type: file, path: verdaccio.log, level: info}

persistence:
  enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires Persistence.Enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  ## Verdaccio data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

  accessMode: ReadWriteOnce
  size: 8Gi
  ## selector can be used to match an existing PersistentVolume
  ## selector:
  ##   matchLabels:
  ##     app: my-app
  selector: {}

  volumes:
  #  - name: nothing
  #    emptyDir: {}
  mounts:
  # - mountPath: /var/nothing
  #   name: nothing
  #   readOnly: true

podSecurityContext:
  fsGroup: 101
securityContext:
  runAsUser: 10001

priorityClass:
  enabled: false
  # name: ""

existingConfigMap: false

# Secrets
secrets:
  # list of users and password for htpasswd plugin
  # This this is mounted as /verdaccio/auth/htpasswd on pods
  htpasswd: []
  # - username: "test"
  #   password: "test"
  # - username: "blah"
  #   password: "blah"

middlewares:
  oidc-ui:
    enabled: true
 
auth:
  oidc-ui:
    org: REQUIRED_GROUP
    client-id: {OIDC_CLIENT_ID}
    client-secret: {OIDC_CLIENT_SECRET}
    oidc-issuer-url: https://login.{url}.com/auth/realms/{realm}
    oidc-username-property: nickname
    oidc-groups-property: groups
 
url_prefix: https://npm.{url}.com

```

**Comment by cmille62** [comment]
Turns out I needed to add this to the values.yaml::

```YAML
extraEnvVars:
  - name: VERDACCIO_PUBLIC_URL
    value: https://npm.{url}.com
```
