### ISSUE TITLE
podLabels in values breaks chart

### ISSUE THREAD

**Issue by blackbass1988** [verdaccio/charts#89]
Hello

I have my-values.yaml

```yaml
podLabels:
  foo: bar
```

helm template verdaccio/verdaccio  --values my-values.yaml

fires error 

Error: YAML parse error on verdaccio/templates/deployment.yaml: error converting YAML to JSON: yaml: line 33: mapping values are not allowed in this context

When I run with --debug I see that

```yaml
---
# Source: verdaccio/templates/deployment.yaml
#....
      labels:
        helm.sh/chart: verdaccio-4.6.1
        app.kubernetes.io/name: verdaccio
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/version: "5.5.0"
        app.kubernetes.io/managed-by: Helm
        app: RELEASE-NAME-verdacciofoo: bar
```

You can seen that there are no EOL after "app: RELEASE-NAME-verdaccio"

dirty hack is adding {{printf "" }} in the end of {{- define "verdaccio.labels" -}}

maybe there are more correct fix

```yaml
{{- define "verdaccio.labels" -}}
helm.sh/chart: {{ include "verdaccio.chart" . }}
{{ include "verdaccio.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app: {{ include "verdaccio.fullname" . }}
{{printf "" }}
{{- end }}
```
