### ISSUE TITLE
pod restarts and npm ERR! cb() never called!

### ISSUE THREAD

**Issue by gauravkcldcvr** [verdaccio/charts#97]
**ENV**:

`helm: verdaccio/verdaccio: 4.8.1`
  
```
 > k get pods -n marketplace
NAME                                    READY   STATUS    RESTARTS   AGE
verdaccio-95887d8-ddwerm2   1/1     Running   71         114d
  
```

Noticing frequent pods restart with below logs, we are running this as a cron job in argo worflow it exits with below logs in the first attempts and manages to run successfully in the second attempt. 

**Container events**: 

```
time="2022-05-09T02:30:04.616Z" level=info msg="capturing logs" argo=true
argopm install <package>

npm WARN using --force I sure hope you know what you are doing.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-09T02_30_57_963Z-debug.log
Error: exit status 1
```

Is this due to running only a single replica considering the utilisation as it has high usage or some misconfiguration that is causing this. Liveliness is failing as well with error - 

`Liveness probe failed: Get "http://10.0.0.229:4873/-/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Config**: 
```
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: verdaccio
          ports:
          - containerPort: 4873
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
```
